name: deploy-github-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cd mazes-in-typescript && npm install && npm run build
      - name: Archive
        run: cd mazes-in-typescript/dist && find . | xargs tar -cf $RUNNER_TEMP/artifact.tar
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{runner.temp}}/artifact.tar
          retention-days: 1
  deploy_github_pages:
    name: Deploy Github Pages
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: build
    steps:
      - name: Deploy Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
