name: deploy-github-pages
on:
  push:
    branches:
      - main
jobs:
  deploy_github_pages:
    name: Deploy Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cd mazes-in-typescript && npm install && npm run build
      - name: Deploy to Github Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: mazes-in-typescript/dist
